create table announcement (
                              id int4 generated by default as identity,
                              description varchar(255),
                              done boolean not null,
                              pathImage varchar(255),
                              body_type_id int4,
                              car_brand_id int4,
                              user_id int4,
                              primary key (id)
);

create table body_type (
                           id int4 generated by default as identity,
                           name varchar(255),
                           primary key (id)
);

create table car_brand (
                           id int4 generated by default as identity,
                           name varchar(255),
                           primary key (id)
);

create table users (
                       id int4 generated by default as identity,
                       name varchar(255),
                       primary key (id)
);

alter table if exists announcement
    add constraint FKkofbc63orts3xn1f83snkkvdm
        foreign key (body_type_id)
            references body_type;

alter table if exists announcement
    add constraint FKqf1l08cdam9y3n2oupid638wf
        foreign key (car_brand_id)
            references car_brand;

alter table if exists announcement
    add constraint FK2h4do02h949v4feor01thar35
        foreign key (user_id)
            references users;